const data = [
  {
    department: "Services",
    company: "Lazz",
    gender: "Polygender",
    language: "Zulu",
    first_name: "Jennee",
    ssn: "225-55-8927",
  },
  {
    department: "Support",
    company: "Minyx",
    gender: "Male",
    language: "West Frisian",
    first_name: "Buiron",
    ssn: "788-76-5956",
  },
  {
    department: "Marketing",
    company: "Shufflester",
    gender: "Genderqueer",
    language: "Hebrew",
    first_name: "Christabella",
    ssn: "617-91-8930",
  },
  {
    department: "Accounting",
    company: "Skilith",
    gender: "Female",
    language: "Georgian",
    first_name: "Gertruda",
    ssn: "206-38-9233",
  },
  {
    department: "Support",
    company: "Flashspan",
    gender: "Female",
    language: "Thai",
    first_name: "Sheelah",
    ssn: "832-92-7737",
  },
  {
    department: "Research and Development",
    company: "Trilith",
    gender: "Female",
    language: "Croatian",
    first_name: "Betti",
    ssn: "419-33-4343",
  },
  {
    department: "Marketing",
    company: "Yodo",
    gender: "Male",
    language: "Polish",
    first_name: "Waldo",
    ssn: "845-11-1241",
  },
  {
    department: "Human Resources",
    company: "Dabtype",
    gender: "Male",
    language: "Tamil",
    first_name: "Buddy",
    ssn: "179-36-8217",
  },
  {
    department: "Human Resources",
    company: "Youspan",
    gender: "Male",
    language: "Northern Sotho",
    first_name: "Land",
    ssn: "607-76-8385",
  },
  {
    department: "Sales",
    company: "Blognation",
    gender: "Male",
    language: "Bulgarian",
    first_name: "Sol",
    ssn: "292-50-9556",
  },
  {
    department: "Training",
    company: "Mynte",
    gender: "Female",
    language: "Malagasy",
    first_name: "Jasmina",
    ssn: "269-51-7882",
  },
  {
    department: "Accounting",
    company: "Realfire",
    gender: "Male",
    language: "Arabic",
    first_name: "Loydie",
    ssn: "311-43-5504",
  },
  {
    department: "Business Development",
    company: "Zoomcast",
    gender: "Male",
    language: "Aymara",
    first_name: "Hubey",
    ssn: "262-68-4865",
  },
  {
    department: "Business Development",
    company: "Zooveo",
    gender: "Female",
    language: "Aymara",
    first_name: "Caroline",
    ssn: "258-53-8011",
  },
  {
    department: "Accounting",
    company: "Realblab",
    gender: "Female",
    language: "Somali",
    first_name: "Annmarie",
    ssn: "764-62-5353",
  },
  {
    department: "Human Resources",
    company: "Lazzy",
    gender: "Male",
    language: "Montenegrin",
    first_name: "Caspar",
    ssn: "851-95-1417",
  },
  {
    department: "Product Management",
    company: "Bubblebox",
    gender: "Male",
    language: "Zulu",
    first_name: "Ennis",
    ssn: "438-89-4576",
  },
  {
    department: "Research and Development",
    company: "Pixoboo",
    gender: "Male",
    language: "Dutch",
    first_name: "Jeffrey",
    ssn: "536-27-9073",
  },
  {
    department: "Product Management",
    company: "Yodo",
    gender: "Female",
    language: "Nepali",
    first_name: "Kimberly",
    ssn: "512-94-7541",
  },
  {
    department: "Accounting",
    company: "Meevee",
    gender: "Female",
    language: "Zulu",
    first_name: "Lenora",
    ssn: "825-02-5263",
  },
  {
    department: "Product Management",
    company: "Divavu",
    gender: "Female",
    language: "Luxembourgish",
    first_name: "Annamarie",
    ssn: "106-31-0275",
  },
  {
    department: "Engineering",
    company: "Rhycero",
    gender: "Female",
    language: "Georgian",
    first_name: "Kelli",
    ssn: "260-06-2965",
  },
  {
    department: "Marketing",
    company: "Trilith",
    gender: "Female",
    language: "Fijian",
    first_name: "Ivonne",
    ssn: "146-33-3940",
  },
  {
    department: "Legal",
    company: "Eire",
    gender: "Female",
    language: "West Frisian",
    first_name: "Nathalia",
    ssn: "263-55-6493",
  },
  {
    department: "Research and Development",
    company: "Eimbee",
    gender: "Male",
    language: "Catalan",
    first_name: "Hersch",
    ssn: "488-97-8570",
  },
  {
    department: "Business Development",
    company: "Yoveo",
    gender: "Male",
    language: "Māori",
    first_name: "Nickie",
    ssn: "570-56-4655",
  },
  {
    department: "Support",
    company: "Jabbersphere",
    gender: "Bigender",
    language: "Dzongkha",
    first_name: "Sherill",
    ssn: "598-84-6838",
  },
  {
    department: "Legal",
    company: "Blogtag",
    gender: "Female",
    language: "Tajik",
    first_name: "Korney",
    ssn: "392-82-9192",
  },
  {
    department: "Marketing",
    company: "Skiba",
    gender: "Female",
    language: "Arabic",
    first_name: "Fern",
    ssn: "147-99-3963",
  },
  {
    department: "Research and Development",
    company: "Oyoyo",
    gender: "Female",
    language: "Tetum",
    first_name: "Leonore",
    ssn: "739-35-1671",
  },
  {
    department: "Support",
    company: "Jatri",
    gender: "Female",
    language: "German",
    first_name: "Sheeree",
    ssn: "725-71-7594",
  },
  {
    department: "Accounting",
    company: "Roodel",
    gender: "Female",
    language: "Yiddish",
    first_name: "Nicola",
    ssn: "895-20-4336",
  },
  {
    department: "Human Resources",
    company: "Edgeclub",
    gender: "Male",
    language: "Zulu",
    first_name: "Kerwin",
    ssn: "363-80-6254",
  },
  {
    department: "Services",
    company: "Dazzlesphere",
    gender: "Female",
    language: "Norwegian",
    first_name: "Jamie",
    ssn: "869-39-7359",
  },
  {
    department: "Support",
    company: "Shufflebeat",
    gender: "Female",
    language: "Portuguese",
    first_name: "Flossy",
    ssn: "543-74-8383",
  },
  {
    department: "Services",
    company: "Yodoo",
    gender: "Female",
    language: "Dhivehi",
    first_name: "Eden",
    ssn: "184-24-0853",
  },
  {
    department: "Product Management",
    company: "Agimba",
    gender: "Male",
    language: "Hungarian",
    first_name: "Donalt",
    ssn: "849-84-2192",
  },
  {
    department: "Legal",
    company: "Oozz",
    gender: "Female",
    language: "Afrikaans",
    first_name: "Lisabeth",
    ssn: "116-54-9192",
  },
  {
    department: "Support",
    company: "Avamba",
    gender: "Female",
    language: "Hindi",
    first_name: "Tedda",
    ssn: "381-42-8405",
  },
  {
    department: "Research and Development",
    company: "Chatterbridge",
    gender: "Female",
    language: "West Frisian",
    first_name: "Johnna",
    ssn: "844-24-1862",
  },
  {
    department: "Legal",
    company: "Kwimbee",
    gender: "Male",
    language: "Catalan",
    first_name: "Normie",
    ssn: "275-15-9741",
  },
  {
    department: "Accounting",
    company: "Camido",
    gender: "Male",
    language: "Tsonga",
    first_name: "Darnell",
    ssn: "670-84-7877",
  },
  {
    department: "Services",
    company: "Twitterbridge",
    gender: "Male",
    language: "Sotho",
    first_name: "Barn",
    ssn: "896-20-9746",
  },
  {
    department: "Services",
    company: "Flipstorm",
    gender: "Bigender",
    language: "Dutch",
    first_name: "Juana",
    ssn: "270-67-8120",
  },
  {
    department: "Human Resources",
    company: "Jetpulse",
    gender: "Male",
    language: "Estonian",
    first_name: "Daven",
    ssn: "360-32-8800",
  },
  {
    department: "Sales",
    company: "Skilith",
    gender: "Female",
    language: "Danish",
    first_name: "Renie",
    ssn: "696-36-5721",
  },
  {
    department: "Legal",
    company: "Zoombeat",
    gender: "Female",
    language: "Kannada",
    first_name: "Emmy",
    ssn: "290-08-7969",
  },
  {
    department: "Accounting",
    company: "Yadel",
    gender: "Male",
    language: "French",
    first_name: "Xavier",
    ssn: "810-68-4198",
  },
  {
    department: "Training",
    company: "Tanoodle",
    gender: "Female",
    language: "Hebrew",
    first_name: "Valentine",
    ssn: "872-91-4034",
  },
  {
    department: "Product Management",
    company: "Vidoo",
    gender: "Bigender",
    language: "Kurdish",
    first_name: "Kitti",
    ssn: "514-52-2326",
  },
  {
    department: "Services",
    company: "Skibox",
    gender: "Male",
    language: "Estonian",
    first_name: "Andros",
    ssn: "260-05-0798",
  },
  {
    department: "Engineering",
    company: "Meezzy",
    gender: "Male",
    language: "Catalan",
    first_name: "Humphrey",
    ssn: "876-97-3745",
  },
  {
    department: "Engineering",
    company: "Trilith",
    gender: "Female",
    language: "Telugu",
    first_name: "Mira",
    ssn: "677-28-9297",
  },
  {
    department: "Services",
    company: "Voomm",
    gender: "Female",
    language: "Sotho",
    first_name: "Carrie",
    ssn: "820-86-6247",
  },
  {
    department: "Training",
    company: "Gabcube",
    gender: "Male",
    language: "Kazakh",
    first_name: "Elmo",
    ssn: "278-29-9561",
  },
  {
    department: "Legal",
    company: "Buzzshare",
    gender: "Male",
    language: "Hindi",
    first_name: "Pablo",
    ssn: "514-21-6451",
  },
  {
    department: "Training",
    company: "Rhynyx",
    gender: "Female",
    language: "Telugu",
    first_name: "Letta",
    ssn: "454-52-6602",
  },
  {
    department: "Research and Development",
    company: "Fanoodle",
    gender: "Male",
    language: "Malagasy",
    first_name: "Esdras",
    ssn: "824-98-3631",
  },
  {
    department: "Human Resources",
    company: "Wikibox",
    gender: "Female",
    language: "Kannada",
    first_name: "April",
    ssn: "472-39-8067",
  },
  {
    department: "Support",
    company: "Dynazzy",
    gender: "Male",
    language: "Aymara",
    first_name: "Bern",
    ssn: "142-61-9877",
  },
  {
    department: "Legal",
    company: "Linklinks",
    gender: "Female",
    language: "Chinese",
    first_name: "Damaris",
    ssn: "756-64-1631",
  },
  {
    department: "Legal",
    company: "Yadel",
    gender: "Male",
    language: "Luxembourgish",
    first_name: "Bailey",
    ssn: "554-43-9221",
  },
  {
    department: "Product Management",
    company: "Dynabox",
    gender: "Male",
    language: "Haitian Creole",
    first_name: "Claiborn",
    ssn: "670-73-2626",
  },
  {
    department: "Support",
    company: "Agimba",
    gender: "Female",
    language: "Bulgarian",
    first_name: "Tandie",
    ssn: "207-66-5819",
  },
  {
    department: "Sales",
    company: "Janyx",
    gender: "Male",
    language: "Czech",
    first_name: "Eduino",
    ssn: "547-89-4373",
  },
  {
    department: "Sales",
    company: "JumpXS",
    gender: "Male",
    language: "Filipino",
    first_name: "Mitchael",
    ssn: "863-93-3134",
  },
  {
    department: "Training",
    company: "Skajo",
    gender: "Male",
    language: "Hebrew",
    first_name: "Bald",
    ssn: "522-71-7271",
  },
  {
    department: "Product Management",
    company: "Skipfire",
    gender: "Female",
    language: "Italian",
    first_name: "Sophi",
    ssn: "458-56-8286",
  },
  {
    department: "Training",
    company: "Trudeo",
    gender: "Male",
    language: "Romanian",
    first_name: "Calhoun",
    ssn: "209-16-3926",
  },
  {
    department: "Sales",
    company: "Snaptags",
    gender: "Female",
    language: "Somali",
    first_name: "Janina",
    ssn: "313-89-4399",
  },
  {
    department: "Product Management",
    company: "Dabshots",
    gender: "Bigender",
    language: "Yiddish",
    first_name: "Darin",
    ssn: "852-71-0463",
  },
  {
    department: "Business Development",
    company: "Zoonder",
    gender: "Female",
    language: "Dzongkha",
    first_name: "Pauline",
    ssn: "593-29-4478",
  },
  {
    department: "Services",
    company: "Ozu",
    gender: "Polygender",
    language: "Icelandic",
    first_name: "Adolphe",
    ssn: "556-10-8404",
  },
  {
    department: "Accounting",
    company: "Mycat",
    gender: "Male",
    language: "Albanian",
    first_name: "Chariot",
    ssn: "426-04-6944",
  },
  {
    department: "Legal",
    company: "Lazzy",
    gender: "Female",
    language: "Bengali",
    first_name: "Terza",
    ssn: "383-55-3304",
  },
  {
    department: "Marketing",
    company: "Omba",
    gender: "Female",
    language: "Assamese",
    first_name: "Sarajane",
    ssn: "381-56-6761",
  },
  {
    department: "Marketing",
    company: "Meetz",
    gender: "Female",
    language: "Icelandic",
    first_name: "Kesley",
    ssn: "204-02-1107",
  },
  {
    department: "Marketing",
    company: "Rhyzio",
    gender: "Female",
    language: "Haitian Creole",
    first_name: "Corine",
    ssn: "866-45-8691",
  },
  {
    department: "Accounting",
    company: "Kanoodle",
    gender: "Female",
    language: "Estonian",
    first_name: "Luci",
    ssn: "157-18-0765",
  },
  {
    department: "Legal",
    company: "Voonder",
    gender: "Male",
    language: "Bulgarian",
    first_name: "Muffin",
    ssn: "510-74-6525",
  },
  {
    department: "Support",
    company: "Kwimbee",
    gender: "Female",
    language: "Bengali",
    first_name: "Maighdiln",
    ssn: "487-86-8811",
  },
  {
    department: "Engineering",
    company: "Shuffledrive",
    gender: "Male",
    language: "Tok Pisin",
    first_name: "Pebrook",
    ssn: "360-53-8900",
  },
  {
    department: "Product Management",
    company: "Tazzy",
    gender: "Male",
    language: "Hungarian",
    first_name: "Gibb",
    ssn: "240-66-8704",
  },
  {
    department: "Product Management",
    company: "Lazz",
    gender: "Male",
    language: "Malay",
    first_name: "Carlie",
    ssn: "570-43-4330",
  },
  {
    department: "Research and Development",
    company: "Wordify",
    gender: "Non-binary",
    language: "Bislama",
    first_name: "Elsworth",
    ssn: "670-99-5420",
  },
  {
    department: "Services",
    company: "Gigabox",
    gender: "Female",
    language: "Māori",
    first_name: "Audrie",
    ssn: "170-05-7562",
  },
  {
    department: "Support",
    company: "Mita",
    gender: "Female",
    language: "Dari",
    first_name: "Yelena",
    ssn: "827-36-0152",
  },
  {
    department: "Human Resources",
    company: "Zoozzy",
    gender: "Male",
    language: "Arabic",
    first_name: "Barnaby",
    ssn: "547-24-0904",
  },
  {
    department: "Business Development",
    company: "Snaptags",
    gender: "Female",
    language: "German",
    first_name: "Shawnee",
    ssn: "273-38-4389",
  },
  {
    department: "Human Resources",
    company: "Realpoint",
    gender: "Female",
    language: "Khmer",
    first_name: "Natty",
    ssn: "474-42-7940",
  },
  {
    department: "Human Resources",
    company: "Edgetag",
    gender: "Genderfluid",
    language: "Malayalam",
    first_name: "Emmit",
    ssn: "738-70-6350",
  },
  {
    department: "Sales",
    company: "Thoughtmix",
    gender: "Male",
    language: "Georgian",
    first_name: "Brenden",
    ssn: "713-64-7272",
  },
  {
    department: "Research and Development",
    company: "Tagtune",
    gender: "Female",
    language: "Mongolian",
    first_name: "Seana",
    ssn: "200-40-2037",
  },
  {
    department: "Business Development",
    company: "Wikizz",
    gender: "Male",
    language: "Burmese",
    first_name: "Rodger",
    ssn: "301-41-1995",
  },
  {
    department: "Product Management",
    company: "Devify",
    gender: "Female",
    language: "Norwegian",
    first_name: "Brenna",
    ssn: "578-99-3666",
  },
  {
    department: "Marketing",
    company: "Leexo",
    gender: "Male",
    language: "Quechua",
    first_name: "Terence",
    ssn: "597-50-7739",
  },
  {
    department: "Training",
    company: "Eazzy",
    gender: "Male",
    language: "Hebrew",
    first_name: "Rory",
    ssn: "709-53-1311",
  },
  {
    department: "Sales",
    company: "Divavu",
    gender: "Agender",
    language: "Belarusian",
    first_name: "Mag",
    ssn: "136-52-5464",
  },
  {
    department: "Accounting",
    company: "LiveZ",
    gender: "Female",
    language: "Quechua",
    first_name: "Katheryn",
    ssn: "271-79-8075",
  },
  {
    department: "Research and Development",
    company: "Yodo",
    gender: "Male",
    language: "Finnish",
    first_name: "Pat",
    ssn: "889-76-2098",
  },
  {
    department: "Engineering",
    company: "Youbridge",
    gender: "Female",
    language: "Bengali",
    first_name: "Tabatha",
    ssn: "600-27-8627",
  },
  {
    department: "Services",
    company: "Thoughtstorm",
    gender: "Female",
    language: "Spanish",
    first_name: "Dania",
    ssn: "512-39-2095",
  },
  {
    department: "Marketing",
    company: "Gigashots",
    gender: "Male",
    language: "Aymara",
    first_name: "Hinze",
    ssn: "605-25-6063",
  },
  {
    department: "Engineering",
    company: "Livefish",
    gender: "Male",
    language: "Indonesian",
    first_name: "Ewan",
    ssn: "525-27-8345",
  },
  {
    department: "Research and Development",
    company: "Rhyzio",
    gender: "Male",
    language: "Hebrew",
    first_name: "Fran",
    ssn: "276-53-8968",
  },
  {
    department: "Business Development",
    company: "Ntags",
    gender: "Female",
    language: "Estonian",
    first_name: "Claudie",
    ssn: "533-90-2273",
  },
  {
    department: "Research and Development",
    company: "Roodel",
    gender: "Male",
    language: "Kurdish",
    first_name: "Rorke",
    ssn: "605-39-4822",
  },
  {
    department: "Legal",
    company: "Mydo",
    gender: "Male",
    language: "Korean",
    first_name: "Murray",
    ssn: "853-03-6419",
  },
  {
    department: "Support",
    company: "Riffpath",
    gender: "Male",
    language: "Moldovan",
    first_name: "Darill",
    ssn: "647-72-3200",
  },
  {
    department: "Support",
    company: "Wordify",
    gender: "Male",
    language: "Hiri Motu",
    first_name: "Whittaker",
    ssn: "158-64-7233",
  },
  {
    department: "Services",
    company: "Thoughtsphere",
    gender: "Non-binary",
    language: "Dari",
    first_name: "Lanny",
    ssn: "639-53-4792",
  },
  {
    department: "Human Resources",
    company: "Topicstorm",
    gender: "Male",
    language: "Kurdish",
    first_name: "Ashby",
    ssn: "614-67-1131",
  },
  {
    department: "Marketing",
    company: "Eare",
    gender: "Male",
    language: "Persian",
    first_name: "Brennen",
    ssn: "635-57-5493",
  },
  {
    department: "Legal",
    company: "Rhycero",
    gender: "Female",
    language: "Georgian",
    first_name: "Octavia",
    ssn: "837-62-5064",
  },
  {
    department: "Product Management",
    company: "Ntag",
    gender: "Male",
    language: "Burmese",
    first_name: "Jeramey",
    ssn: "693-89-1248",
  },
  {
    department: "Engineering",
    company: "Voolia",
    gender: "Male",
    language: "Aymara",
    first_name: "Lancelot",
    ssn: "815-19-0493",
  },
  {
    department: "Services",
    company: "Quimm",
    gender: "Female",
    language: "Dzongkha",
    first_name: "Lilly",
    ssn: "122-18-5374",
  },
  {
    department: "Research and Development",
    company: "Vimbo",
    gender: "Male",
    language: "Kashmiri",
    first_name: "Matt",
    ssn: "588-69-0112",
  },
  {
    department: "Services",
    company: "Flashpoint",
    gender: "Male",
    language: "Irish Gaelic",
    first_name: "Byrom",
    ssn: "731-68-8793",
  },
  {
    department: "Research and Development",
    company: "Tazz",
    gender: "Male",
    language: "Filipino",
    first_name: "Yvon",
    ssn: "421-90-6561",
  },
  {
    department: "Product Management",
    company: "Divavu",
    gender: "Female",
    language: "Kurdish",
    first_name: "Vicki",
    ssn: "311-51-3612",
  },
  {
    department: "Sales",
    company: "Eire",
    gender: "Male",
    language: "Greek",
    first_name: "Zeke",
    ssn: "176-83-8690",
  },
  {
    department: "Sales",
    company: "Bubbletube",
    gender: "Male",
    language: "Romanian",
    first_name: "Charlton",
    ssn: "423-01-6319",
  },
  {
    department: "Support",
    company: "Plajo",
    gender: "Male",
    language: "Gagauz",
    first_name: "Tannie",
    ssn: "117-78-4776",
  },
  {
    department: "Legal",
    company: "Avamm",
    gender: "Male",
    language: "Finnish",
    first_name: "Des",
    ssn: "423-95-5057",
  },
  {
    department: "Business Development",
    company: "Chatterpoint",
    gender: "Female",
    language: "Somali",
    first_name: "Jacquenette",
    ssn: "615-40-9865",
  },
  {
    department: "Business Development",
    company: "Zazio",
    gender: "Polygender",
    language: "Thai",
    first_name: "Tony",
    ssn: "786-04-0489",
  },
  {
    department: "Marketing",
    company: "Aivee",
    gender: "Female",
    language: "Swati",
    first_name: "Sisely",
    ssn: "606-96-2090",
  },
  {
    department: "Training",
    company: "Twitterwire",
    gender: "Male",
    language: "Azeri",
    first_name: "Lutero",
    ssn: "332-16-3245",
  },
  {
    department: "Support",
    company: "Jabbercube",
    gender: "Female",
    language: "Hebrew",
    first_name: "Vitoria",
    ssn: "704-36-0206",
  },
  {
    department: "Research and Development",
    company: "Centizu",
    gender: "Female",
    language: "Romanian",
    first_name: "Malva",
    ssn: "692-47-0495",
  },
  {
    department: "Business Development",
    company: "Voonder",
    gender: "Male",
    language: "Dhivehi",
    first_name: "Benjamin",
    ssn: "698-57-1493",
  },
  {
    department: "Business Development",
    company: "Jabbercube",
    gender: "Male",
    language: "Latvian",
    first_name: "Joey",
    ssn: "120-33-4098",
  },
  {
    department: "Product Management",
    company: "Quinu",
    gender: "Female",
    language: "Marathi",
    first_name: "Jaynell",
    ssn: "208-28-9230",
  },
  {
    department: "Support",
    company: "Camido",
    gender: "Female",
    language: "Dzongkha",
    first_name: "Orel",
    ssn: "299-79-3923",
  },
  {
    department: "Engineering",
    company: "Katz",
    gender: "Female",
    language: "Haitian Creole",
    first_name: "Marleah",
    ssn: "866-84-5993",
  },
  {
    department: "Support",
    company: "Youopia",
    gender: "Female",
    language: "Czech",
    first_name: "Devina",
    ssn: "194-56-2762",
  },
  {
    department: "Engineering",
    company: "Youspan",
    gender: "Polygender",
    language: "Swedish",
    first_name: "Trenton",
    ssn: "798-10-7243",
  },
  {
    department: "Support",
    company: "Ainyx",
    gender: "Female",
    language: "Spanish",
    first_name: "Allina",
    ssn: "735-64-9660",
  },
  {
    department: "Support",
    company: "Livefish",
    gender: "Female",
    language: "Romanian",
    first_name: "Donia",
    ssn: "836-70-7369",
  },
  {
    department: "Business Development",
    company: "Babbleset",
    gender: "Male",
    language: "Dzongkha",
    first_name: "Onfre",
    ssn: "165-53-2959",
  },
  {
    department: "Services",
    company: "Blognation",
    gender: "Female",
    language: "Hindi",
    first_name: "Ana",
    ssn: "398-10-6478",
  },
  {
    department: "Support",
    company: "Innojam",
    gender: "Female",
    language: "Croatian",
    first_name: "Brianne",
    ssn: "315-87-0494",
  },
  {
    department: "Marketing",
    company: "Zoombeat",
    gender: "Female",
    language: "Moldovan",
    first_name: "Kettie",
    ssn: "276-38-2267",
  },
  {
    department: "Accounting",
    company: "Camido",
    gender: "Female",
    language: "Dzongkha",
    first_name: "Clementia",
    ssn: "635-52-7117",
  },
  {
    department: "Training",
    company: "Meetz",
    gender: "Female",
    language: "Mongolian",
    first_name: "Jenica",
    ssn: "883-83-1316",
  },
  {
    department: "Legal",
    company: "Meembee",
    gender: "Male",
    language: "Nepali",
    first_name: "Granville",
    ssn: "743-03-4259",
  },
  {
    department: "Services",
    company: "Layo",
    gender: "Genderqueer",
    language: "Dhivehi",
    first_name: "Fredelia",
    ssn: "492-01-7722",
  },
  {
    department: "Services",
    company: "Dablist",
    gender: "Female",
    language: "Montenegrin",
    first_name: "Rori",
    ssn: "733-74-9920",
  },
  {
    department: "Support",
    company: "Vipe",
    gender: "Male",
    language: "Zulu",
    first_name: "Marcellus",
    ssn: "290-71-3252",
  },
  {
    department: "Marketing",
    company: "Viva",
    gender: "Male",
    language: "Burmese",
    first_name: "Federico",
    ssn: "597-79-0602",
  },
  {
    department: "Human Resources",
    company: "Jabberstorm",
    gender: "Female",
    language: "French",
    first_name: "Sheena",
    ssn: "482-54-9716",
  },
  {
    department: "Legal",
    company: "Vitz",
    gender: "Male",
    language: "Korean",
    first_name: "Rollin",
    ssn: "267-54-4258",
  },
  {
    department: "Business Development",
    company: "Oozz",
    gender: "Male",
    language: "Japanese",
    first_name: "Iain",
    ssn: "589-69-0907",
  },
  {
    department: "Product Management",
    company: "Pixoboo",
    gender: "Female",
    language: "Tetum",
    first_name: "Nichole",
    ssn: "235-28-0954",
  },
  {
    department: "Business Development",
    company: "Topicblab",
    gender: "Agender",
    language: "Icelandic",
    first_name: "Brucie",
    ssn: "477-23-3522",
  },
  {
    department: "Research and Development",
    company: "Miboo",
    gender: "Male",
    language: "Kashmiri",
    first_name: "Nick",
    ssn: "128-08-4289",
  },
  {
    department: "Product Management",
    company: "Eamia",
    gender: "Male",
    language: "Nepali",
    first_name: "Reinaldo",
    ssn: "530-33-3431",
  },
  {
    department: "Legal",
    company: "Tekfly",
    gender: "Female",
    language: "Dari",
    first_name: "Marylou",
    ssn: "662-70-9395",
  },
  {
    department: "Engineering",
    company: "Dabvine",
    gender: "Female",
    language: "Estonian",
    first_name: "Nanete",
    ssn: "370-69-3683",
  },
  {
    department: "Accounting",
    company: "Rhybox",
    gender: "Female",
    language: "Marathi",
    first_name: "Isabella",
    ssn: "359-43-3015",
  },
  {
    department: "Legal",
    company: "Oyoyo",
    gender: "Female",
    language: "Hindi",
    first_name: "Marlo",
    ssn: "595-66-0205",
  },
  {
    department: "Accounting",
    company: "Thoughtstorm",
    gender: "Male",
    language: "Moldovan",
    first_name: "Kirk",
    ssn: "327-04-7136",
  },
  {
    department: "Accounting",
    company: "Topicstorm",
    gender: "Female",
    language: "Pashto",
    first_name: "Simona",
    ssn: "149-72-6133",
  },
  {
    department: "Sales",
    company: "Lazzy",
    gender: "Female",
    language: "Fijian",
    first_name: "Lezlie",
    ssn: "506-72-4579",
  },
  {
    department: "Engineering",
    company: "Brainsphere",
    gender: "Female",
    language: "Zulu",
    first_name: "Alyda",
    ssn: "244-99-5414",
  },
  {
    department: "Training",
    company: "Devpulse",
    gender: "Male",
    language: "Malay",
    first_name: "Elbert",
    ssn: "896-53-2933",
  },
  {
    department: "Accounting",
    company: "Thoughtmix",
    gender: "Female",
    language: "Guaraní",
    first_name: "Carolina",
    ssn: "376-65-6235",
  },
  {
    department: "Marketing",
    company: "Rhybox",
    gender: "Male",
    language: "Bislama",
    first_name: "Mordecai",
    ssn: "289-23-3641",
  },
  {
    department: "Marketing",
    company: "Feedfish",
    gender: "Male",
    language: "Bulgarian",
    first_name: "Riley",
    ssn: "545-70-6552",
  },
  {
    department: "Legal",
    company: "Chatterpoint",
    gender: "Male",
    language: "Papiamento",
    first_name: "Malvin",
    ssn: "248-59-5489",
  },
  {
    department: "Sales",
    company: "Wikizz",
    gender: "Female",
    language: "Korean",
    first_name: "Tracey",
    ssn: "696-58-6101",
  },
  {
    department: "Human Resources",
    company: "Omba",
    gender: "Female",
    language: "English",
    first_name: "Emilia",
    ssn: "348-13-9449",
  },
  {
    department: "Product Management",
    company: "Oyoyo",
    gender: "Male",
    language: "Bengali",
    first_name: "Rodrique",
    ssn: "440-04-7508",
  },
  {
    department: "Human Resources",
    company: "JumpXS",
    gender: "Female",
    language: "Assamese",
    first_name: "Ronnica",
    ssn: "393-88-3518",
  },
  {
    department: "Services",
    company: "Vipe",
    gender: "Male",
    language: "Kashmiri",
    first_name: "Baily",
    ssn: "270-37-5951",
  },
  {
    department: "Research and Development",
    company: "DabZ",
    gender: "Female",
    language: "Dzongkha",
    first_name: "Rosamond",
    ssn: "462-22-8354",
  },
  {
    department: "Sales",
    company: "Dablist",
    gender: "Male",
    language: "Dari",
    first_name: "Tanny",
    ssn: "612-30-7749",
  },
  {
    department: "Support",
    company: "Babbleopia",
    gender: "Bigender",
    language: "Fijian",
    first_name: "Rand",
    ssn: "233-31-7527",
  },
  {
    department: "Legal",
    company: "Oloo",
    gender: "Male",
    language: "Oriya",
    first_name: "Andris",
    ssn: "841-08-2079",
  },
  {
    department: "Sales",
    company: "Gabvine",
    gender: "Male",
    language: "Nepali",
    first_name: "Madison",
    ssn: "238-19-4247",
  },
  {
    department: "Business Development",
    company: "Skiba",
    gender: "Female",
    language: "Dutch",
    first_name: "Allie",
    ssn: "521-55-9950",
  },
  {
    department: "Engineering",
    company: "JumpXS",
    gender: "Male",
    language: "Punjabi",
    first_name: "Rob",
    ssn: "101-29-0187",
  },
  {
    department: "Marketing",
    company: "Thoughtworks",
    gender: "Female",
    language: "Swahili",
    first_name: "Daron",
    ssn: "373-35-5045",
  },
  {
    department: "Legal",
    company: "Fadeo",
    gender: "Male",
    language: "Zulu",
    first_name: "Tommie",
    ssn: "793-59-3150",
  },
  {
    department: "Engineering",
    company: "Edgepulse",
    gender: "Male",
    language: "Aymara",
    first_name: "Hadleigh",
    ssn: "818-31-3020",
  },
  {
    department: "Product Management",
    company: "Thoughtbeat",
    gender: "Female",
    language: "Assamese",
    first_name: "Christean",
    ssn: "535-41-1364",
  },
  {
    department: "Support",
    company: "Mynte",
    gender: "Male",
    language: "Oriya",
    first_name: "Urbanus",
    ssn: "318-01-9421",
  },
  {
    department: "Product Management",
    company: "Topicstorm",
    gender: "Male",
    language: "Sotho",
    first_name: "Jermain",
    ssn: "829-38-5546",
  },
  {
    department: "Support",
    company: "Blogspan",
    gender: "Male",
    language: "New Zealand Sign Language",
    first_name: "Bourke",
    ssn: "804-48-7808",
  },
  {
    department: "Support",
    company: "Feedbug",
    gender: "Male",
    language: "Portuguese",
    first_name: "Jarid",
    ssn: "238-74-3416",
  },
  {
    department: "Product Management",
    company: "Skynoodle",
    gender: "Female",
    language: "Swahili",
    first_name: "Lola",
    ssn: "402-91-7175",
  },
  {
    department: "Accounting",
    company: "Tavu",
    gender: "Genderqueer",
    language: "Gujarati",
    first_name: "Eduino",
    ssn: "316-27-8168",
  },
  {
    department: "Sales",
    company: "Yamia",
    gender: "Female",
    language: "Gujarati",
    first_name: "Doroteya",
    ssn: "132-67-2216",
  },
  {
    department: "Research and Development",
    company: "Browsedrive",
    gender: "Female",
    language: "Estonian",
    first_name: "Cherilyn",
    ssn: "594-76-2799",
  },
  {
    department: "Engineering",
    company: "Trilith",
    gender: "Male",
    language: "Italian",
    first_name: "Yehudi",
    ssn: "662-29-5611",
  },
  {
    department: "Training",
    company: "Digitube",
    gender: "Male",
    language: "Korean",
    first_name: "Antonino",
    ssn: "379-33-6314",
  },
  {
    department: "Accounting",
    company: "Meemm",
    gender: "Genderqueer",
    language: "Luxembourgish",
    first_name: "Darius",
    ssn: "311-79-7717",
  },
  {
    department: "Research and Development",
    company: "BlogXS",
    gender: "Male",
    language: "Tok Pisin",
    first_name: "Xymenes",
    ssn: "804-11-3794",
  },
  {
    department: "Product Management",
    company: "Kwideo",
    gender: "Male",
    language: "Sotho",
    first_name: "Patton",
    ssn: "722-86-2226",
  },
];

// 1. Engineering 부서만 가져와서 콘솔 출력
const result1 = data.filter((x) => x.department == "Engineering");

// 2. 성별이 남성, 일본어 쓰면 어디부서이고 이름만 가져와서 출력
const result2 = data
  .filter((x) => x.gender == "Male" && x.language == "Japanese")
  .map((x) => {
    const newData = { department: x.department, first_name: x.first_name };
    return newData;
  });
//   map return { department: x.department, first_name: x.first_name }

// 3. ssn에서 맨 뒤 마지막 자리가 짝수이고, 퍼스트이름이 K,B,S로 시작하는 사람만 가져오기
const result3 = data.filter(
  (x) =>
    Number(x.ssn[x.ssn.length - 1]) % 2 == 0 &&
    ["K", "B", "S"].some((y) => x.first_name.startsWith(y))
);
console.log(result3);

// korean,japanese,chinese 사용하고
// 성별은 여성이고,
// ssn 앞의 세숫자의 합이 10이상

const result4 = data
  .filter(
    (x) =>
      x.language == "korean" ||
      x.language == "japanese" ||
      x.language == "chinese"
  )
  .filter((x) => x.gender === "Female")
  .filter((x) => {
    // const first = x.ssn.split("-")[0];
    // return Number(first[0]) + Number(first[1]) + Number(first[2]) > 10;
    const first = [...x.ssn];
    return Number(first[0]) + Number(first[1]) + Number(first[2]) > 10;
  });

console.log(result4);
